/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gomoku;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author jeffthechef14
 */
public class CellView extends javax.swing.JPanel {
    
    //vars
    private int row, col;
    private boolean locked;
    private Color theColor;
    private boolean clicked;
    
    private Color myColor = Color.blue;
    private Color enemyColor = Color.orange;
    private Color blank = Color.white;

    /**
     * Creates new form CellView
     */
    public CellView() {
        initComponents();
    }
    
    public CellView(int row, int col) {
        initComponents();
        this.row = row;
        this.col = col;
        this.locked = false;
        this.theColor = Color.white;
        this.clicked = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cellBTN = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(28, 28));
        setMinimumSize(new java.awt.Dimension(28, 28));
        setPreferredSize(new java.awt.Dimension(28, 28));

        cellBTN.setBackground(new java.awt.Color(200, 200, 200));
        cellBTN.setMaximumSize(new java.awt.Dimension(28, 28));
        cellBTN.setMinimumSize(new java.awt.Dimension(28, 28));
        cellBTN.setPreferredSize(new java.awt.Dimension(28, 28));
        cellBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cellBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cellBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cellBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cellBTNActionPerformed
  
    public int getRow(){
        return this.row;
    }
    
    public int getCol(){
        return this.col;
    }
    
    public void lockCell(){
        this.locked = true;
    }
    
    public boolean isLocked(){
        return this.locked;
    }
    
    public boolean isClicked(){
        return this.clicked;
    }
    
    public void cellListener(ActionListener listenerForClick){
        cellBTN.addActionListener(listenerForClick);
    }
    
    public void setText(String text){
        cellBTN.setText(text);
    }
    
    public void eraseText(){
        cellBTN.setText(null);
    }
    
    public void click(){
        if(this.clicked = true){
            setCellColor(blank);
            this.clicked = false;
        }
        else{
            this.clicked = true;
            setCellColor(myColor);
        }
    }
    
    public void setCellColor(Color theColor){
        this.theColor = theColor;
        cellBTN.setBackground(theColor);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cellBTN;
    // End of variables declaration//GEN-END:variables
}
