package gomoku;

import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author heyitsjeoff
 */
public class ServerGUI extends javax.swing.JPanel {

    /**
     * Creates new form ServerGUI
     */
    public ServerGUI() {
        initComponents();
    }
    
    /**
     * appends users who log in
     * @param a logged in user
     */
    public void appendStringList(String a){
        onlineListTA.append(a);
        onlineListTA.append("\n");
    }
    
    /**
     * displays the ip address of the server
     * @param ip string representing ip
     */
    public void displayIP(String ip){
        ipLabel.setText(ip);
    }
    
    /**
     * displays a message
     * @param a new label
     */
    public void message(String a){
        messageLabel.setText(a);
    }
    
    /**
     * Updates the Text Area of online users with all users that are online and
     * already logged in
     * @param listOfOnline 
     */
    public void updateOnline(ArrayList<Client> listOfOnline){
        onlineListTA.setText("");
        for(Client c: listOfOnline)
            appendStringList(c.toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        onlineListTA = new javax.swing.JTextArea();
        onlineUsersLabel = new javax.swing.JLabel();
        ipLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        onlineListTA.setColumns(14);
        onlineListTA.setRows(5);
        jScrollPane3.setViewportView(onlineListTA);

        onlineUsersLabel.setText("Online Users");

        ipLabel.setText("IP");

        messageLabel.setText("System Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageLabel)
                    .addComponent(ipLabel)
                    .addComponent(onlineUsersLabel)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(onlineUsersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ipLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ipLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextArea onlineListTA;
    private javax.swing.JLabel onlineUsersLabel;
    // End of variables declaration//GEN-END:variables
}
